/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_doom119_ffmpegtest_MainActivity */

#ifndef _Included_com_doom119_ffmpegtest_MainActivity
#define _Included_com_doom119_ffmpegtest_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_doom119_ffmpegtest_MainActivity
 * Method:    prepareFFmpeg
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_doom119_ffmpegtest_MainActivity_prepareFFmpeg
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
